"""Guide RNA capability schemas.

Source: section 8 of the engine capability system design. Section 8.2 gives the
request schema, section 8.6 gives `OffTargetSpace`, and section 8.7 gives the
output surface (ranked guide table, per guide reasoning, cloning oligos, the
off-target space statement, the validation report).

Three notes on how this file relates to section 8.2.

1. Section 8.2 lists five request fields. Five more are added here, every one
   of them optional with a default, because three of the nine section 8.5
   checks cannot be evaluated without them and section 3.3 constraint 4 says a
   check that cannot be evaluated returns UNKNOWN rather than PASS:

   * `grna.self_targeting` needs the delivery construct sequence.
   * `grna.u6_terminator` has a severity that depends on whether the guide is
     U6 driven, so the expression system has to be stated.
   * `grna.position_in_cds` needs the coding sequence and final exon spans.
   * `grna.restriction_in_spacer` needs the cloning strategy enzyme, which
     comes from the chosen vector.

   Absent any of these the owning check reports UNKNOWN with the reason, so the
   section 8.2 fields alone still produce a usable, honest result.

2. `OffTargetSpace.label` is section 8.6's field and it defaults to the empty
   string here. The authoritative text shown in the UI and in exports is
   `OffTargetSummary.space_statement`, which the code generates from what was
   actually searched. A request supplied label is never shown in its place, so
   a label cannot overstate the search (section 16).

3. Scores carry their model name, their model kind (a published model or a
   labeled heuristic), their citation, their validity domain and the word
   prediction, because section 8.4 and section 16 require all of those at the
   point of display.

Coordinates follow the convention in `models.py` and `capability.py`:
zero-based, start inclusive, end exclusive, always on the supplied forward
target sequence so they can be used directly for display.
"""

from __future__ import annotations

from typing import Any, Literal

from pydantic import Field, field_validator, model_validator

from .capability import CapabilityKind, CapabilityModel, ValidationReport

NucleaseName = Literal["SpCas9", "SaCas9", "LbCas12a", "AsCas12a"]
"""The four supported nucleases, exactly as section 8.2 spells them."""

EditIntent = Literal["knockout", "knockin", "activation", "interference"]
"""Section 8.2 edit intents."""

ExpressionSystem = Literal["u6_plasmid", "t7_in_vitro", "other"]
"""How the guide reaches the cell.

Needed because section 8.5 check 4 is FAIL when the guide is U6 driven and WARN
otherwise, and because the on-target model in section 8.4 has an expression
system in its validity domain.
"""

HostContext = Literal[
    "human_cell_line",
    "mouse_cell_line",
    "other_mammalian",
    "non_mammalian",
    "cell_free",
]
"""Biological context of the edit, used only to decide whether a published
on-target model is inside its stated validity domain (section 8.4)."""

OffTargetScope = Literal["construct_only", "supplied_fasta", "none"]
"""Section 8.6 scopes."""

ModelKind = Literal["published_model", "labeled_heuristic"]
"""Section 8.4: a published model and a transparent heuristic are different
things and must never be displayed as the same thing."""

ScoreStatus = Literal["in_domain", "in_domain_with_caveat", "out_of_domain"]
"""Section 8.4: a request outside the model's trained context gets the score
with an explicit caveat, or no score at all. Never a silent extrapolation."""


class OffTargetSpace(CapabilityModel):
    """Section 8.6, reproduced field for field.

    `label` is optional here. The text actually shown is generated by
    `packages.validation.grna.offtarget.space_statement` from the sequences that
    were really searched, including their real total size, and lands in
    `OffTargetSummary.space_statement`.
    """

    scope: OffTargetScope
    fasta_path: str | None = None
    label: str = ""

    @model_validator(mode="after")
    def fasta_path_required_for_supplied_fasta(self) -> OffTargetSpace:
        if self.scope == "supplied_fasta" and not (self.fasta_path or "").strip():
            raise ValueError("scope 'supplied_fasta' requires fasta_path")
        if self.scope != "supplied_fasta" and self.fasta_path:
            raise ValueError(f"fasta_path is only meaningful for scope 'supplied_fasta', not {self.scope!r}")
        return self


class GuideRNARequest(CapabilityModel):
    """Section 8.2, plus the five defaulted fields explained in the module docstring."""

    target_sequence: str = Field(min_length=1)
    target_name: str = Field(min_length=1)
    nuclease: NucleaseName = "SpCas9"
    edit_intent: EditIntent
    off_target_space: OffTargetSpace
    max_guides_returned: int = Field(default=10, ge=1, le=1000)
    # Rule Set 1 stays the default so existing requests behave exactly as before.
    # "rule_set_2" asks for the 2016 Azimuth model, which runs in a container and
    # falls back to Rule Set 1 with the fallback named in the score if unavailable.
    on_target_model: Literal["rule_set_1", "rule_set_2"] = "rule_set_1"

    expression_system: ExpressionSystem = "u6_plasmid"
    host_context: HostContext = "human_cell_line"
    delivery_construct_name: str | None = None
    delivery_construct_sequence: str | None = None
    cloning_vector: str | None = None  # key into CLONING_VECTORS; None selects the nuclease default
    cds_region: tuple[int, int] | None = None  # coding sequence span inside target_sequence
    final_exon_region: tuple[int, int] | None = None  # final exon span inside target_sequence
    constitutive_regions: tuple[tuple[int, int], ...] = ()  # spans present in every transcript

    @field_validator("cds_region", "final_exon_region")
    @classmethod
    def span_ordered(cls, value: tuple[int, int] | None) -> tuple[int, int] | None:
        if value is None:
            return value
        start, end = value
        if start < 0 or end <= start:
            raise ValueError("a span must satisfy 0 <= start < end (zero-based, end exclusive)")
        return value

    @field_validator("constitutive_regions")
    @classmethod
    def spans_ordered(cls, value: tuple[tuple[int, int], ...]) -> tuple[tuple[int, int], ...]:
        for start, end in value:
            if start < 0 or end <= start:
                raise ValueError("a span must satisfy 0 <= start < end (zero-based, end exclusive)")
        return value


class GuideSpec(CapabilityModel):
    """The single guide a validation run is about.

    `spacer` and `pam` are written 5' to 3' on the strand the guide targets, the
    way section 8.7 requires them displayed. `spacer_start` is the zero-based
    start of the spacer on the supplied forward target sequence; when it is
    omitted the validator locates the spacer in the target, which lets a gold
    case name a guide by sequence alone.
    """

    spacer: str = Field(min_length=1)
    pam: str = Field(min_length=1)
    strand: Literal[1, -1] = 1
    spacer_start: int | None = Field(default=None, ge=0)


class Placement(CapabilityModel):
    """Where a guide sits on the forward target sequence, with its cut sites.

    Every interval is zero-based, start inclusive, end exclusive, on the
    supplied forward sequence, whatever the strand. `pam_observed` is what the
    target actually reads at the PAM interval the nuclease geometry dictates,
    which is what makes a wrong PAM offset visible rather than silent
    (Appendix C).
    """

    strand: Literal[1, -1]
    spacer_start: int
    spacer_end: int
    pam_start: int
    pam_end: int
    pam_observed: str
    pam_side: Literal["three_prime", "five_prime"]
    cut_site: int
    cut_site_staggered: int | None = None
    context_30mer: str | None = None  # guide-strand 30mer when the flanks exist, else None


class ScoreContribution(CapabilityModel):
    """One term of a score, for the per guide reasoning section 8.7 requires."""

    feature: str
    detail: str
    weight: float
    direction: Literal["up", "down", "neutral"]


class OnTargetScore(CapabilityModel):
    """A predicted on-target activity, with everything section 8.4 and section 16 demand.

    `score` is None when the request falls outside `validity_domain`. It is
    never filled in by extrapolation.
    """

    model_name: str = Field(min_length=1)
    model_kind: ModelKind
    citation: str = Field(min_length=1)
    validity_domain: str = Field(min_length=1)
    status: ScoreStatus
    score: float | None = None
    score_scale: str = "0 to 100, higher is more active"
    caveats: list[str] = Field(default_factory=list)
    reasoning: list[ScoreContribution] = Field(default_factory=list)
    disclaimer: str = Field(min_length=1)

    @model_validator(mode="after")
    def out_of_domain_has_no_score(self) -> OnTargetScore:
        if self.status == "out_of_domain" and self.score is not None:
            raise ValueError("an out_of_domain on-target result must not carry a score (section 8.4)")
        if self.status != "out_of_domain" and self.score is None:
            raise ValueError("an in-domain on-target result must carry a score")
        if self.status != "in_domain" and not self.caveats:
            raise ValueError("a caveated or out-of-domain score must state at least one caveat")
        return self


class OffTargetHit(CapabilityModel):
    """One site in the searched space that the guide could bind.

    `mismatch_positions` are 1-based positions along the spacer written 5' to
    3', so position `len(spacer)` is the PAM-proximal end for a 3' PAM
    nuclease. `seed_mismatches` counts those inside the PAM-proximal seed
    window (Appendix C, 8 to 12 nt, configurable).
    """

    source_id: str = Field(min_length=1)
    source_label: str = Field(min_length=1)
    start: int
    end: int
    strand: Literal[1, -1]
    protospacer: str = Field(min_length=1)
    pam: str = Field(min_length=1)
    pam_is_alternative: bool = False
    mismatches: int = Field(ge=0)
    mismatch_positions: tuple[int, ...] = ()
    seed_mismatches: int = Field(ge=0)
    hit_score: float | None = None  # published per-site score, None when out of domain
    hit_score_status: ScoreStatus = "in_domain"
    is_on_target: bool = False


class OffTargetSummary(CapabilityModel):
    """The searched space, stated verbatim, plus what was found in it (section 8.6)."""

    scope: OffTargetScope
    space_statement: str = Field(min_length=1)  # shown verbatim in the UI and in every export
    searched_sequence_count: int = Field(ge=0)
    searched_bases: int = Field(ge=0)
    searched_sequences: list[str] = Field(default_factory=list)
    max_mismatches_searched: int = Field(ge=0)
    seed_region_nt: int = Field(ge=0)
    hits: list[OffTargetHit] = Field(default_factory=list)
    specificity_model_name: str = Field(min_length=1)
    specificity_citation: str = Field(min_length=1)
    specificity_validity_domain: str = Field(min_length=1)
    specificity_status: ScoreStatus
    specificity_score: float | None = None  # aggregate guide specificity, None when out of domain
    disclaimer: str = Field(min_length=1)
    searched: bool = True
    notes: list[str] = Field(default_factory=list)


class CloningOligo(CapabilityModel):
    """One orderable oligonucleotide, written 5' to 3' (section 8.7)."""

    name: str = Field(min_length=1)
    sequence: str = Field(min_length=1)
    role: str = Field(min_length=1)
    five_prime_overhang: str = ""
    three_prime_addition: str = ""
    length_nt: int = Field(ge=1)
    notes: list[str] = Field(default_factory=list)

    @model_validator(mode="after")
    def length_matches(self) -> CloningOligo:
        if self.length_nt != len(self.sequence):
            raise ValueError("length_nt must equal len(sequence)")
        return self


class CloningPlan(CapabilityModel):
    """Everything needed to order and clone one guide into one vector."""

    vector_id: str = Field(min_length=1)
    vector_name: str = Field(min_length=1)
    vector_source: str = Field(min_length=1)
    digest_enzyme: str | None = None
    protocol_reference: str | None = None
    oligos: list[CloningOligo] = Field(default_factory=list)
    notes: list[str] = Field(default_factory=list)


class GuideRNADesign(CapabilityModel):
    """One guide RNA design: the request context plus the single guide under validation.

    This is the model the capability registers as its `design_model`, so a gold
    case input is exactly `{"request": {...}, "guide": {...}}`.
    """

    request: GuideRNARequest
    guide: GuideSpec


class RankedGuide(CapabilityModel):
    """A row of the section 8.7 ranked guide table, with its reasoning attached."""

    rank: int = Field(ge=1)
    guide_id: str = Field(min_length=1)
    spacer: str = Field(min_length=1)  # written 5' to 3'
    pam: str = Field(min_length=1)
    pam_motif: str = Field(min_length=1)
    pam_is_alternative: bool = False
    strand: Literal[1, -1]
    placement: Placement
    on_target: OnTargetScore
    off_target: OffTargetSummary
    report: ValidationReport
    flags: list[str] = Field(default_factory=list)
    reasoning: list[str] = Field(default_factory=list)
    cloning: CloningPlan | None = None


class GuideRNAResult(CapabilityModel):
    """Section 8.7 output surface for a whole request."""

    capability: CapabilityKind = CapabilityKind.GUIDE_RNA
    design_id: str = Field(min_length=1)
    target_name: str = Field(min_length=1)
    nuclease: NucleaseName
    guides_enumerated: int = Field(ge=0)
    guides_returned: list[RankedGuide] = Field(default_factory=list)
    off_target_space_statement: str = Field(min_length=1)  # verbatim, repeated at the top level
    rejected: list[dict[str, Any]] = Field(default_factory=list)
    notes: list[str] = Field(default_factory=list)
    parameters_used: dict[str, Any] = Field(min_length=1)
    provenance: list[str] = Field(min_length=1)
